# Generated by Django 3.2.13 on 2023-05-18 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='vote',
            new_name='vote_average',
        ),
    ]
